    name: Actions Workflow

    on: [push]

    jobs:
      run-github-actions:
          runs-on: ubuntu-latest
          steps:
            - name: Simple JS Actions
              id: greet
              uses: actions/hello-world-javascript-action@main
              with: 
                who-to-greet: Stefan

            - name: Log Greeting Time
              run: echo ${{ steps.greet.outputs.time }}
